### PR TITLE
Added Abstract Type: Email

### PR DESCRIPTION
**Pull request by cambiata**
Simple and hopefully usable example of abstract types (?)

### CODE REVIEW

**Comment by nadako** [comment]
Looks cute! I think you should use `haxe` tag after opening fences though so highlighter knows the language.

**Comment by nadako** [comment]
Also, I'd made that Ereg static so it's not created on each `Email` instantiation.

**Comment by nadako** [comment]
Also, I think it's more logical to check and throw before assigning to `this`.

**Comment by Gama11** [comment]
Maybe `EmailAddress` would be a better name? My initial thought when reading the PR title was that this would be for an actual email / the content, with a `send()` method or whatnot... :D

**Comment by markknol** [comment]
Very nice, with suggestions above and tags added it is good to go :)

**Comment by nadako** [comment]
Also feel free to add "author" field at the bottom, if you want (see example https://github.com/HaxeFoundation/code-cookbook/blob/master/assets/content/cookbook/Principles/everything-is-an-expression.md)

**Comment by cambiata** [comment]
Thank you, guys!
Didn't know that it was possible to use 'static' in abstracts! :-)

**Comment by markknol** [comment]
It's online!

I did some extra small updates to it.

**Comment by cambiata** [comment]
Cool! Thanks!

**Pull request merged**
