### PR TITLE
add enum abstract values macro

### PR DESCRIPTION
**Pull request by nadako**

### CODE REVIEW

**Comment by nadako** [comment]
@Simn I wonder if we really want to expose the `@:enum @:impl` implementation details.

**Comment by Simn** [comment]
What would you do instead?

**Comment by nadako** [comment]
I don't know, provide this functionality in Std? I don't remember why I was against it.
My concern is that this snippet can become obsolete if we decide to change something in the enum abstract implementation.

**Comment by Simn** [comment]
I'm not against it, but it's a bit late to add more API for 3.3...

**Comment by nadako** [comment]
Maybe I just should mention in this snippet that it uses current implementation...

**Comment by nadako** [comment]
I added a small note about usage of implementation detail

**Pull request merged**
