### PR TITLE
Javascript inline web workers

### PR DESCRIPTION
**Pull request by cambiata**
Example demonstrating how to create inline web workers (parent and worker combined in the same .js script).

### CODE REVIEW

**Comment by ibilon** [comment]
It's using several untyped which is bad practice, why do you require it?

From what I could understand self refers to the object, which should be what the haxe this does,
or is it [window.self](http://api.haxe.org/js/html/Window.html#self)?

**Comment by cambiata** [comment]
Thanks for feedback, @ibilon !

I've removed the lazy DOM-"untyped".

When it comes to the worker "self", I'm still grabbing it using "untyped self", but I now type the resulting variable as js.html.DedicatedWorkerGlobalScope. Can't figure out a better way of doing it...

**Comment by markknol** [comment]
Nice article!

Some notes:
* Can you also write "JavaScript" everywhere?
* inline code should have one `, only block should have 3 ```
* I found `uInt8View` confusing, can it be `uint8View`

**Comment by cambiata** [comment]
Thanks! Done. 
(Appreciate your attention to detail.)

**Comment by cambiata** [comment]
This example doesn't work on try.haxe.org.
Don't know if there's any dedicated js example site where it should work...

**Comment by markknol** [comment]
I think you can create a folder called "assets" next to your example and put stuff in there, and use relative links. Havent tried with html pages but should work.. :o :)

**Comment by markknol** [comment]
What is left to do here? Its a good article, can it be put live?

If you have demo I can link it+host on cookbook site.

**Comment by markknol** [comment]
For now Ill just merge it o/ Its sad if this nice article stays on holder. If there are any other contributions you can just PR as always 👍 Thanks !

**Pull request merged**
