### PR TITLE
Append a builder for Linux/OSX and gaft the footer on the bottom of t…

### PR DESCRIPTION
**Pull request by xvw**
Append a builder for Linux/OSX and gaft the footer on the bottom of the page (using flex)

### CODE REVIEW

**Comment by markknol** [comment]
Thanks! The update is online.

**Comment by markknol** [comment]
This doesn't work in Internet Explorer
image

**Comment by markknol** [comment]
I fixed it like this https://github.com/HaxeFoundation/code-cookbook/commit/e68957fa092e307f23661d6ca52562c33e7e33db

**Comment by xvw** [comment]
Yeah, it seems good. 
Sorry for the mistake ;)

**Pull request merged**
