### PR TITLE
Added abstract type: Precision Float

### PR DESCRIPTION
**Pull request by cambiata**
Hi!

Got the idea of an abstract to get rid of the tedious float rounding errors.
I'm not really sure about the name - "Precision Float" is a bit misleading, as it's based on standard Float, and doesn't have higher precision, it just covers the errors by rounding them away...
Please suggest a better name!

Also, I might have missed important stuff when it comes to this floating point aritmetic area... Please enlighten me about problems and dangers with the example code.
(As a start, I have added a disclaimer text about potential dangers...)

### CODE REVIEW

**Comment by Gama11** [comment]
`RoundedFloat`?

**Comment by cambiata** [comment]
@Gama11 Yep, that's better. Will change!

**Comment by cambiata** [comment]
Done!

**Comment by markknol** [comment]
Youre on a roll! thanks!

**Comment by markknol** [comment]
Does this also work when the float is high,like in a million?

**Comment by cambiata** [comment]
Hm, the line 21 should be changed to
```
  // The number of zeros in the following valuer
  // corresponds to the number of decimals rounding precision
  static inline var multiplier = 10000000;
```

**Comment by cambiata** [comment]
`...to avoid quickly accumulated errors to overflow the rounding.

**Pull request merged**
