### PR TITLE
Advanced version of extract-enum-value

### PR DESCRIPTION
**Pull request by romamik**

### CODE REVIEW

**Comment by markknol** [comment]
What exactly does this more advanced than http://code.haxe.org/category/macros/extract-enum-value.html?
Wouldn't it be an idea to put both on the same page, explaining the difference/advantage of using one or the other?

**Comment by romamik** [comment]
It allows to extract multiple values.
    
    Match.extract(Node(Leaf("leaf0"), Leaf("leaf1")), Node(Leaf(leafName0), Leaf(leafName1)));
    
will return
    
    {leafName0:"leaf0", leafName1:"leaf1"}
      
which is not possible with already existing version.
And, yes, you know better where to put it. If you say to put this on the same page, then I can do it.

**Comment by nadako** [comment]
I think it's fine to have a separate page for this, but maybe we should put links to each other :)

Also this does not compile currently with Haxe 4 due to change in `EObjectDecl` argument: there was an optional field added and the structure is now `typedef`'d to `ObjectField`. Specifying it as the return type to the mapping function is enough, but there's no such typedef on Haxe 3...

I guess mentioning this somehow would be helful.

**Comment by markknol** [comment]
Ill just merge this

**Pull request merged**
