### PR TITLE
First draft of ssl-socket-server.md

### PR DESCRIPTION
**Pull request by jcward**
[Rendered version](https://github.com/jcward/code-cookbook/blob/patch-3/assets/content/cookbook/Other/ssl-socket-server.md)

### CODE REVIEW

**Comment by PXshadow** [comment]
You are an absolute legend, I can't believe you figured it out.

**Comment by markknol** [comment]
Looks very good, please let me know when it is ready to merge?

**Comment by jcward** [comment]
@PXshadow - :laughing: 

@markknol - I added info about where to get test certs, so anyone should be able to get the example working. At some point it'd be great to sort it out on Windows... I'm not sure if you'd rather hold off on publishing until then.

**Comment by markknol** [comment]
Let's merge it! If you or someone else has the details for Windows, feel free to do additional PR. 
Thanks for your contribution!

**Pull request merged**
