### PR TITLE
Basic Cppia tutorials

### PR DESCRIPTION
**Pull request by cambiata**
Two recepies, one for creating and testing a cppia script - the other for creating and testing a host.

### CODE REVIEW

**Comment by markknol** [comment]
I wonder if this is content for the manual or code haxe site.

cc @Simn

**Comment by Simn** [comment]
Well, it's here now, so we might as well use it.

**Comment by markknol** [comment]
I think this is a good candidate for a serie https://github.com/HaxeFoundation/code-cookbook/issues/59

**Comment by markknol** [comment]
I've implemented it in https://github.com/HaxeFoundation/code-cookbook/issues/62

**Pull request closed without merging**
