### PR TITLE
Added code snippet on adding map field when building type.

### PR DESCRIPTION
**Pull request by dstrekelj**
Hello,

I added an entry on how to handle map creation via macro. It is (loosely) inspired by a recent [discussion](https://groups.google.com/forum/#!searchin/haxelang/map$20macro%7Csort:date/haxelang/30GbfrO00JU/SrqmHj3_AAAJ) on the Haxe mailing list.

Hopefully it's a common enough use-case to warrant a place in the cookbook :)

Regards,
Domagoj

### CODE REVIEW

**Comment by markknol** [comment]
Nice addition, thanks for the contribution! The line before the author needs two spaces at the end to add a linebreak in markdown. Now it displays as one line.

**Comment by Simn** [comment]
This could be made more natural by passing the array as argument to the macro call instead of declaring it locally. This would mean working with Expr instead of String, but that shouldn't require too many changes.

**Comment by dstrekelj** [comment]
@markknol Nice catch! Somehow my Markdown preview package in Atom missed that.

@Simn I hope I understood you correctly. I added an argument for the array of strings to be hashed so the macro works like Nicolas' "Code completion from URL". In case I missed the mark, could you elaborate on what you meant when you have time?

**Comment by Simn** [comment]
Ah, I didn't realize it would work with `Array<String>` like that. See, I'm learning things too thanks to this project!

Anyway, that's exactly what I meant.

**Pull request merged**
