### PR TITLE
Create pipe.md

### PR DESCRIPTION
**Pull request by PongoEngine**
Adding an example to demonstrate operator overloading.

### CODE REVIEW

**Comment by Aurel300** [comment]
Could you run the code through the formatter? I mostly noticed the spaces around `:`, which are generally not used in the rest of the cookbook.

**Comment by markknol** [comment]
I did some formatting + small updates.

I don't understand where the pipe2, pipe3, pipe4 etc are needed for? It seems to work without too: https://try.haxe.org/#633402C3

**Comment by Aurel300** [comment]
`pipe2` etc would be needed if you used methods which took more than one argument.

**Comment by PongoEngine** [comment]
Thank you for the formatting. It looks great. I'll make sure to use a formatter next time.

**Comment by PongoEngine** [comment]
Are there any other tasks left on my end? I'm happy to add to the article or make changes.

**Comment by markknol** [comment]
No, it is all good! Thanks! Will be live in few minutes (when CI passes).

**Pull request merged**
