### PR TITLE
Emulating named function parameters

### PR DESCRIPTION
**Pull request by x2f**
A very simple use of anonymous structures can increase code readability, especially for functions with lots of parameters.

### CODE REVIEW

**Comment by dstrekelj** [comment]
@markknol might have something to say about your inclusion of string interpolation :P From what I remember, it's an 'unspoken rule' not to mix concepts / features, especially if they haven't been covered before in the cookbook. In this case it might be okay, though, because the entry itself is relatively short.

I'd maybe expand on the disclaimer about the good and bad sides of named parameters in Haxe. They're not there by design for a reason, so I feel like 'hacking' them in should warrant a debate (the performance impact you have touched upon is a good start). But that's just me nitpicking :)

**Comment by markknol** [comment]
Hi thanks for your contribution! Im fine with the string interpolation in this case. Can you write Haxe with capital? Also can you add tags? See readme and check existing tags. 
I wait a bit for @simn feedback on this before this snippet gets added.

**Comment by markknol** [comment]
Btw @simn I am starting to feel uncorfortable with the "other" category, can you help with some new category names?

**Comment by x2f** [comment]
Thanks for the comments. @markknol: fixed Haxe with capital and added a tag. @dstrekelj: you have a good point that it's not in the language probably for a reason. I don't know what to add beyond the fact that it has a performance impact (in particular I don't know the extend of this impact). Any additional input on this would indeed be nice.

**Comment by dstrekelj** [comment]
@back2dos discusses the effect named parameters can have on Haxe code in his [tink_lang](https://github.com/haxetink/tink_lang) repository, particularly in the [section covering the named parameter macro](https://github.com/haxetink/tink_lang#named-parameter-caveats).

A shortened version of the above, with proper attribution to the original author, would be a nice addition to the recipe. If both @markknol and @back2dos agree, of course.

Again, I'm no authority figure here. I'm just worried that newcomers might get the wrong idea if we present them a 'feature' that's not really there.

**Comment by back2dos** [comment]
@dstrekelj The reservations I elaborated on apply to the particular language extension that tink provides (and equally to first class support for named parameters in the core language - unless names become part of function types which would pretty much sabotage structural subtyping).

The approach described here is - in my opinion - highly advisable, so long as it's not used in a performance critical section (in which case there are still viable options to reduce overhead). And since it is clearly about *emulating* named parameters, I don't think there's anything misleading about it.

A link to tink_lang's alternative might interest readers, although haxelib statistics suggest that practically nobody actually dares use the library.

**Comment by markknol** [comment]
@back2dos the stats on haxelib were broken for a very long time.

**Comment by x2f** [comment]
Thanks @dstrekelj & @back2dos. The Tinker Bell Extensions readme is an interesting read. Looks like a nice example on how to extend Haxe as well. I updated the page to clarify pros/cons and added a reference to Tinker Bell.

**Comment by Simn** [comment]
I don't like this example because it's totally arbitrary. If you want to showcase something like this at least make a practical example, e.g. passing configuration parameters for something.

Furthermore, the impact on performance isn't accurate. The primary problem here is not the dynamic lookup (though that is bad enough already) but the fact that an object is created in the first place.

**Comment by x2f** [comment]
Hi @Simn thanks for the comments. I like the idea of using this for configuration (though it's not possible to have defaults: you need to give all config values). I can update the page with something like this and also mention the object creation as an additional factor for the performance impact. 

On another side, I'd like to know if you guys would just prefer to let this go and abandon the topic. No big deal. Nevertheless, if you think it's worth continuing I'd be happy to, especially it can be useful to expose the drawbacks, and warn people away from this technique except in specific cases (long list of params, rare calls).

**Comment by back2dos** [comment]
> Furthermore, the impact on performance isn't accurate. The primary problem here is not the dynamic lookup (though that is bad enough already) but the fact that an object is created in the first place.

Not necessarily. The dynamic lookup is the more expensive bit on [both the JVM (by far) and CLR (although barely)](https://gist.github.com/back2dos/bcba3e2943dc77601c2bed55d1367b82).

On other static and all dynamic platforms, the converse is true of course.

---

As for the general question: yes, I think investigating this is worthwhile. I have mentioned this elsewhere, but I think it would be interesting to use this context to point out that this gives you the best of both worlds:

```haxe
public inline function foo(options:{ x:Int, y:Float, z:String }) return _foo(options.x, options.y, options.z);
private function _foo(x:Int, y:Float, z:String) return "$x, $y, $z";
```

In that case the analyzer is usually able to avoid creating the anonymous object altogether.

I absolutely agree with Simn that the whole article would illustrate the usefulness of the technique in a far more convincing way, if you could aim for more realworldish application, e.g. `sys.db.Mysql.connect`.

**Comment by x2f** [comment]
Ok @back2dos, the page is now updated with an example using neko.db.Mysql.connect and a performance considerations section. Much of the performance info is copied from you so I added you as an author.

**Comment by markknol** [comment]
I think it is complete now, feel free to PR additions if needed. Thanks for the contributions all!

**Pull request merged**
