### PR TITLE
Latest update to replace existing Haxe-To-Emscripten-Hello-World.md file

### PR DESCRIPTION
**Pull request by Fhalo48**

### CODE REVIEW

**Comment by markknol** [comment]
I don't understand this patch, it looks like there are two files now? https://github.com/HaxeFoundation/code-cookbook/pull/129/files

**Comment by Fhalo48** [comment]
Hi

I can't seem to resolve conflicts?

**Comment by ibilon** [comment]
I fixed the conflict, but you still need to remove the duplicate Haxe-To-Emscripten-Hello-World.md file.

**Comment by Fhalo48** [comment]
Do I still need to do anything?

**Comment by ibilon** [comment]
Mark wanted you to put the problem/solution sections at the end,
which I agree makes more sense.

**Pull request merged**
