### PR TITLE
Added article on the Observer design pattern

### PR DESCRIPTION
**Pull request by matrefeytontias**

### CODE REVIEW

**Comment by Gama11** [comment]
This should probably use a type parameter (`Observer<T>`) instead of `Dynamic`.

**Comment by matrefeytontias** [comment]
There's no need to put constraints on the data passed. Instead, somebody would create a Message class, which would in turn have a type parameter.

**Comment by markknol** [comment]
on try.haxe you can use `using Test.Observables` to use static extensions.

**Comment by matrefeytontias** [comment]
Good call, thanks !

**Comment by markknol** [comment]
Thanks for you contribution, it is merged now.

**Pull request merged**
