### PR TITLE
Added article about target specific files

### PR DESCRIPTION
**Pull request by cambiata**

### CODE REVIEW

**Comment by Aurel300** [comment]
This seems to me to mostly duplicate the [manual page](https://haxe.org/manual/lf-target-specific-files.html) …

**Comment by cambiata** [comment]
Yep, that's true. Because I didn't know that the manual page existed when I started creating the article... :-) This feature is one of Haxe's many well-kept secrets, and as a Haxe beginner, if you don't know that this feature exists, you don't know where to look for it. (So it might have a place in code.haxe.org after all..?)

Another idea is that this feature id presented in an article about target-specific conditional compilation. The current [conditional compilation](https://code.haxe.org/category/beginner/conditional-compilation.html) article doesn't cover the option to write target-specific code at all...
Is that better, you think?

**Comment by uvtc** [comment]
This is a cool feature that I didn't know about.

I don't think there's anything particularly wrong with having a cookbook article that is similar to a part or parts of the manual, as those two docs have different aims.

Some aims of the various docs:

  * [manual](https://haxe.org/manual/introduction.html): reference manual
  * [API docs](https://api.haxe.org/): more reference
  * [cookbook](https://code.haxe.org/): instruction by example, how-to docs
  * tutorial (not yet present): instruction for newcomers
  * [blog](https://haxe.org/blog/): articles containing more discussion on various specific topics in the manual
  * [quick getting-started guides](https://haxe.org/documentation/introduction/) to get hello-world running for various targets

**Comment by Aurel300** [comment]
I think the commit you just pushed was meant for a different branch/PR?

**Comment by cambiata** [comment]
Ah, sorry... Was a bit to quick there... Should be deleted now.

**Comment by markknol** [comment]
Looks good to me, thanks!

**Pull request merged**
