### PR TITLE
Added generating-code-in-a-macro example

### PR DESCRIPTION
**Pull request by jcward**
Hey @markknol - whether or not we take more of the article, I think this example stands nicely on its own. Let me know what you think. Cheers!

### CODE REVIEW

**Comment by markknol** [comment]
:+1:  Thanks! I've updated some formatting and added a tag to it.

**Comment by jcward** [comment]
Uh oh, my first paragraph bullets didn't come out on the website:

screenshot_20160616-040219

Do you know how to fix this? Can we not use bullets?

**Comment by Simn** [comment]
You might need a blank line there.

**Comment by markknol** [comment]
I added it, it's there in a minute.

**Comment by jcward** [comment]
Thanks!

**Pull request merged**
