### PR TITLE
Added function-overloading

### PR DESCRIPTION
**Pull request by mrcdk**
It explains some ways to get function overloading in Haxe.

There are probably more ways but I can't think of more.

Should I explain the metadata `@:overload()` and `haxe.extern.EitherType` here?

### CODE REVIEW

**Comment by Simn** [comment]
We are considering to remove the optional argument skipping for Haxe 4, so I'm not sure if we want to showcase it right now.

**Comment by mrcdk** [comment]
:fearful: why?! I can't find any discussion about the topic and I use argument skipping a lot :sob:

**Comment by Simn** [comment]
It's very error-prone, you can easily accidentally skip an argument. It gets even worse when types get more complicated.

**Comment by nadako** [comment]
That reminds me that we wanted to add `extern inline` method overloading.

**Comment by nadako** [comment]
Anyway, I think all these examples are not really overloading in the usual definition (i.e. selecting method by argument number and types), these are about passing different value types in a type-safe manner.

Until Haxe implements some kind of overloading mechanism for non-extern classes, I think the only "real" overloading snippet would be a macro method that checks types of its arguments and dispatches calls to different "overloaded" methods.

**Comment by mrcdk** [comment]
You are right @nadako I guess I'll close this and open a new one someday when I have time

**Pull request closed without merging**
